apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["printenv"]
    env:
    - name: MESSAGE
      value: "Hello World!"
    command: ["/bin/echo"]
    args: ["$(HOSTNAME)", "$(KUBERNETES_PORT)", "$(MESSAGE)"]
  restartPolicy: OnFailure