apiVersion: v1
kind: Pod
metadata:
  name: cpu-demmo
  labels:
    name: cpu-demmo
spec:
  containers:
  - name: cpu-demmo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5" # usar metade do meu cpu
    args:
      - -cpus
      - "2"
