apiVersion: v1
kind: Pod
metadata:
  name: envvar-demo
  labels:
    purpose: demonstrate-envvars
spec:
  containers:
  - name: envvar
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: DEMO_GREETING
      value: "Hello World!!!"