apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
      - mountPath: /data/redis
        name: redis-storage
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: redis-storage
      emptyDir: {} # diretório vazio, vai durar a vida do pod, o container pode reiniciar que esse volume vai durar até o pode for deletado.
